language: python
python:
  - "3.5"  
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
script:
  - pytest --cov=./
after_success:
  - curl -s https://codecov.io/bash | bash
